[[CURRENCIES]]
code="STELLAREU"
issuer="GALN76JFY2ROUGZB2P4YRYFAHZTBUF4ZKSJ7ENUTG7CJNFFUNG6KYFUL"
display_decimals=7
name="STELLAREU"
desc="Token was made by Fomo developer. The amazing European token for your investment"
